---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-backup-percona
stringData:
  rclone.conf: |
    [minio]
    type = s3
    provider = Minio
    access_key_id = access_key
    secret_access_key = secret_key
    endpoint = http://minio:9000
    acl = public-read
    bucket_acl = public-read
  backup.crontab: |
    ## run backup at 00:10
    10 0 * * * root /usr/local/bin/backup.sh |tee -a /tmp/backup.sh.log
