name: Build the image

on:
  push:
    tags:
      - '**'

env:
  IMAGE_NAME: ''
  IMAGE_VERSION: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set variable
      run: |
        set -x
        # example tags refs/tags/zalando-pgbouncer.1
        # get the last part for tags and register into IMAGE_NAME and IMAGE_VERSION
        echo ${GITHUB_REF} | awk -F/ '{print $NF}' | IFS='.' read -r imagename imageversion

        echo "IMAGE_NAME=$imagename, IMAGE_VERSION=$imageversion"

        echo "IMAGE_NAME=$imagename" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$imageversion" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build image
      run: |
        set -exu

        cd $IMAGE_NAME

        docker build --tag ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_VERSION .
        docker push ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_VERSION

        docker tag ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_VERSION ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
        docker push ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
