name: Build the image

on:
  push:
    tags:
      - '**'

env:
  IMAGE_NAME: ''
  IMAGE_VERSION: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set variable
      run: |
        set -x
        # example tags refs/tags/zalando-pgbouncer.1
        # get the last part for tags and register into IMAGE_NAME and IMAGE_VERSION
        ## below line not work
        #echo ${GITHUB_REF} | awk -F/ '{print $NF}' | IFS='.' read -r imagename imageversion

        tags=$(echo ${GITHUB_REF} | awk -F/ '{print $NF}')
        imagename=$(cut -d. -f1 <<<"$tags")
        imageversion=$(cut -d. -f2- <<<"$tags")

        echo "IMAGE_NAME=$imagename, IMAGE_VERSION=$imageversion"

        echo "IMAGE_NAME=$imagename" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$imageversion" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: |
        set -exu

        cd $IMAGE_NAME

        ## set label for the image
        echo "LABEL image_path='https://github.com/${GITHUB_REPOSITORY}/$IMAGE_NAME'" >> Dockerfile

        docker build --tag ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_VERSION .
        docker push ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_VERSION

        docker tag ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_VERSION ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
        docker push ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
